= Rapport d’avancement: groupe “7.4”
PACT groupe 7.4


ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée


:sectnums!:
== « Co-Emplettes »

=== Membres du groupe

* Emile Le Gallic
* Lancelot Portal
* Mody Ba
* Théo MONNET
* Emma Vasiliu
##

=== Tuteur

* Enzo TARTAGLIONE

=== Encadrant génie logiciel

* xx yy

<<<

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Co-Emplettes est une application pour les courses entre les étudiants du plateau.

Les étudiants qui s’occupent de la livraison sont rémunérés pour le transport.

Il peut s’agir de personnes en voiture ou bien de cyclistes. Les étudiants paieraient alors un petit surplus pour la livraison qui servira à la rémunération du livreur. Cette rémunération pourrait également être complétée à l’aide de publicités sur l’application, idéalement pour des évènements étudiants ou certaines enseignes de distribution, voire pourquoi pas des entreprises ou producteurs locaux.

L’application rassemble tous les drives dans un certain rayon autour du plateau et s’occupe de calculer quel commerce est à privilégier selon plusieurs critères (temps de trajet pour le conducteur, prix, disponibilités…).

Un système de Locker, dans lequel les courses seront disposées par le livreur, sera mis en place afin que chaque personne puisse venir récupérer ses courses dans un endroit froid selon son emploi du temps.

L’application pourrait aussi intégrer la livraison pour les groupes en résidence universitaire, dans le cas où aucun étudiant livreur ne soit disponible. L’application privilégiera toujours la livraison par un étudiant.

Bien que le drive soit l’option par défaut, on pourrait imaginer une option spéciale pour les produits frais pour que le livreur aille chercher les produits dans le magasin. Cela permettrait de choisir des produits plus ou moins mûrs. Pour faire gagner du temps, on peut envisager de cartographier les commerces dans ces zones spécifiques. La vérification se fera via une photo du ticket de caisse.

== English Summary (PAN1)

Co-Emplettes is an app allowing students around the Télécom Paris campus to shop for groceries together. 

The student who delivers the groceries to the others is paid. They can go to the supermarket by car or by bike. The other students would then pay a small fee for the delivery which would be used to pay the student buying the groceries. This remuneration could also be supplemented by advertisements on the application, ideally for student events or certain retailers, or even local businesses or producers.

The application gathers all the Drives in a certain radius around the plateau and calculates which business is to be preferred according to several criteria (travel time for the driver, price, availability...). 

A Locker system, in which the groceries will be arranged by the driver, will be set up so that each person can come and pick up his groceries in a cold place according to his schedule. 

The application could also integrate delivery for groups in university residences, in case no student delivery person is available. The app will always favor delivery by a student. 

While drive-through is the default option, one could imagine a special option for fresh produce to have the delivery person pick up the produce in the store. This would allow for a choice of more or less ripe products. To save time, we could consider mapping the shops in these specific areas. Verification would be done via a photo of the receipt. 


<<<

*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autres:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
différents fichiers) se trouve dans le fichier courant.

**Prenez le temps** de supprimer le texte de remplissage et les sections non
utilisées pour l'instant. Vous pouvez par exemple commenter ces parties non
utilisées pour qu'elles n'apparaissent pas dans le document final. En Asciidoc,
il suffit de les précéder de deux slashs (`//`).

<<<
toc::[]
<<<

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

<<<

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
