=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

*_Note : 1 page max._*

Décrivez, en les citant via la bibliographie, les approches/produits
ressemblant à votre projet et les différences éventuelles. Illustrez
avec des images si besoin. Utilisez des renvois vers votre
bibliographie : « comme démontré dans [2], … »

Notre projet s'ancre dans un cadre d'applications 
en forte augmentation ces derniers temps : la livraison de courses/repas.
Dès lors, il est possible de distinguer différents produits
existants qui se rapproche de notre projet.

==== Application de livraison de nourriture : Uber Eat, Deliveroo, Just Eat...

Les applications de type "livraison de nourriture" <<UberEat>> ont d'abord eu 
comme principale fonction d'être un intermédiaire entre les restaurateurs
et les clients proposant à ces derniers des livraisons par 
des livreurs employés dans le cadre du service et 
rémunérés pour la course en question.
Ce modèle s'est récemment développé et popularisé auprès des
chaines de grande distribution et commerces de proximités 
qui proposent désormais également leurs services de livraison 
sur ces mêmes plateformes.

C'est sur le principe de livraison que notre application 
se rapproche des exemples cités précédemment.

Cependant, notre application se démarque par plusieurs aspects :
* le statut des livreurs : il s'agit d'étudiants qui ne sont pas
employé par une quelconque structure mais qui réalise des missions
rémunérées librement.
* le principe des courses groupées : dans notre projet, les commandes de plusieurs clients sont réunies pour une seule 
livraison et ensuite séparées dans les Lockers
* l'aspect économique : quand la majorité des applications
citées ci-dessus ont des prix affichés plus élevés que les prix
en magasin, notre application propose la recherche des prix 
les plus avantageux en proposant au livreur un itinéraire d'achat
visant à minimiser le cout total des courses pour permettre
aux étudiants de payer leurs courses au prix des grandes surfaces
soit inférieur au prix des commerces de proximité du plateau
et des applications de livraison.

==== Les Drives des grandes surfaces et la livraison à domicile

Les courses au Drive sont une solution que nous exploitons dans le projet.
Le principe du Drive est simple : le client passe sa commande en ligne et
vient la récupérer en voiture à un créneau choisi dans le super/hypermarché de son choix (le service Drive est rarement proposé dans les petites surfaces). Cela permet un gain de temps et une meilleure gestion de l'emploi du temps pour le client.

Avec la crise sanitaire, les grands distributeurs se sont mis aussi à proposer une livraison des courses à domicile (comme Leclerc <<Service livraison Leclerc>>), qui est un service intéressant si la commande passée est conséquente, ce qui n'est pas forcément le cas pour un étudiant qui vit souvent seul.

Le projet se sert des services Drive de plusieurs magasins pour simplifier la tâche de l'étudiant-livreur. Il s'inspire aussi de la livraison à domicile, en ajoutant le système de mise en commun de la commande.
